name: 03-Understanding Runners
on: push
jobs:
  runner-info-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print runner details
        run: |
          echo "Workflow is executing on a GitHub-hosted runner"
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architechture: $RUNNER_ARCH"